version: '3.9'
name: currency_app_dev
services:
  currency_db:
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./currency_db-data:/var/lib/postgresql/data
    networks:
      - currency-dev

  currency_api:
    build:
      context: ./
      dockerfile: ./backend/currency_api/Dockerfile
    command:  bash -c 'while !</dev/tcp/currency_db/5432; do sleep 1; done;
      alembic -c backend/currency_api/alembic.ini upgrade head;
      uvicorn backend.currency_api.main:app --reload --log-config backend/currency_api/config/log.ini --host 0.0.0.0 --port 8000'
    ports:
      - "8000:8000"
    volumes:
      - ./backend/currency_api:/terexov_testovoe/backend/currency_api
      - ./logs-data:/terexov_testovoe/logs
    environment:
      - POSTGRES_HOST=currency_db
      - REDIS_URL=redis://redis:6379/
      - LOG_FILE_PATH=logs/currency_api.log
    depends_on:
      - "redis"
      - "currency_db"
    networks:
      - currency-dev

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - currency-dev
  
  rabbitmq:
    image: rabbitmq:3.13.2-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - currency-dev
  
  celery_worker:
    build:
      context: ./
      dockerfile: ./backend/currency_api/Dockerfile
    command: celery -A backend.currency_api.celery.worker:celery worker --loglevel=WARNING --concurrency=2 -f logs/currency_api.log
    volumes:
      - ./backend/currency_api:/terexov_testovoe/backend/currency_api
      - ./logs-data:/terexov_testovoe/logs
    environment:
      - POSTGRES_HOST=currency_db
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - LOG_FILE_PATH=logs/currency_api.log
    depends_on:
      - "redis"
      - "rabbitmq"
      - "currency_db"
      - "currency_api"
    networks:
      - currency-dev

  celery_beat:
    build:
      context: ./
      dockerfile: ./backend/currency_api/Dockerfile
    command: celery -A backend.currency_api.celery.worker:celery beat --loglevel=WARNING -f logs/currency_api.log
    volumes:
      - ./backend/currency_api:/terexov_testovoe/backend/currency_api
      - ./logs-data:/terexov_testovoe/logs
    environment:
      - POSTGRES_HOST=currency_db
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - LOG_FILE_PATH=logs/currency_api.log
    depends_on:
      - "redis"
      - "rabbitmq"
      - "currency_db"
      - "currency_api"
    networks:
      - currency-dev
  
  flower:
    build:
      context: ./
      dockerfile: ./backend/currency_api/Dockerfile
    command: celery -A backend.currency_api.celery.worker:celery flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - "rabbitmq"
      - "currency_api"
      - "celery_worker"
    networks:
      - currency-dev

  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    command:  bash -c 'npm run dev -- --host'
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    networks:
      - currency-dev

networks:
  currency-dev:
    driver: bridge

volumes:
  currency_db-data:
  logs-data: