"""initial

Revision ID: 2458e63452cb
Revises: 
Create Date: 2024-06-29 13:24:21.067714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2458e63452cb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('currency',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('currency_group_id', sa.Integer(), nullable=False),
    sa.Column('num_code', sa.Numeric(precision=3, scale=0), nullable=False),
    sa.Column('char_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['currency_group_id'], ['currency_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('char_code'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('num_code')
    )
    op.create_table('currency_rate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('nominal', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(precision=4), nullable=False),
    sa.Column('vunit_rate', sa.Float(), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currency_rate')
    op.drop_table('currency')
    op.drop_table('currency_group')
    # ### end Alembic commands ###
